/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e2e4d2",
        "surface-container-highest": "#e4e2dd",
        outline: "#73796f",
        "primary-fixed-dim": "#afd0a1",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#062104",
        "on-tertiary-fixed": "#1a1d12",
        "primary-container": "#4a6741",
        primary: "#334f2b",
        "secondary-container": "#feae87",
        "error-container": "#ffdad6",
        "tertiary-container": "#5e6153",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f1ec",
        "on-secondary-container": "#793f21",
        "primary-fixed": "#caecbc",
        "surface-variant": "#e4e2dd",
        "on-primary-fixed-variant": "#324e2a",
        secondary: "#8c4e2e",
        "secondary-fixed": "#ffdbcb",
        "surface-dim": "#dbdad5",
        "on-error": "#ffffff",
        "surface-container": "#f0eee9",
        "tertiary-fixed-dim": "#c5c8b7",
        "surface-bright": "#fbf9f4",
        surface: "#fbf9f4",
        background: "#fbf9f4",
        "on-error-container": "#93000a",
        "on-primary-container": "#c2e4b4",
        "on-tertiary-fixed-variant": "#45483b",
        "on-tertiary-container": "#dadcca",
        tertiary: "#46493c",
        "on-secondary-fixed-variant": "#6f3819",
        "surface-container-low": "#f5f3ee",
        "on-surface-variant": "#434840",
        "on-tertiary": "#ffffff",
        "on-background": "#1b1c19",
        "outline-variant": "#c3c8bd",
        "secondary-fixed-dim": "#ffb692",
        "on-secondary-fixed": "#341100",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "inverse-primary": "#afd0a1",
        "surface-tint": "#496640",
        "on-surface": "#1b1c19",
        "inverse-surface": "#30312e",
        "surface-container-high": "#eae8e3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        unit: "8px",
        "margin-mobile": "16px",
        "container-max": "1200px",
        "margin-desktop": "40px",
        gutter: "24px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "headline-xl": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
